**Geogebra.** File in drive.

In [ ]:
import numpy as np

**Matrix Algebra**

In [ ]:
M

[[1, 2], [3, 4]]

In [ ]:
N = np.array(M)

In [ ]:
N

array([[1, 2],
       [3, 4]])

In [ ]:
# N^2 matrix
np.dot(N, N)

array([[ 7, 10],
       [15, 22]])

In [ ]:
# scalar multiplication
2 * N

array([[2, 4],
       [6, 8]])

In [ ]:
# subtraction
N - N

array([[0, 0],
       [0, 0]])

In [ ]:
# vector [3, 3]
v = np.array([3, 3])

# matrix vector multiplication
np.dot(N, v)

array([ 9, 21])