**Geogebra.** Visualizing vector algebra.

### Boolean Indexing

In [ ]:
import numpy as np

Selecting elements of an array

In [ ]:
# construct array
arr = np.array([12, 24, 16, 21, 32, 29, 7, 15])
arr

array([12, 24, 16, 21, 32, 29,  7, 15])

In [ ]:
# construct a boolean mask by >20 condition
boolMask = arr > 20
boolMask

array([False,  True, False,  True,  True,  True, False, False])

In [ ]:
# select elements of the array by that mask
arr[ boolMask ]

array([24, 21, 32, 29])

In [ ]:
# remainder by 2 is zero, i.e even numbers
boolMask = arr % 2 == 0
arr[ boolMask ]

array([12, 24, 16, 32])

In [ ]:
~ np.array([ True, False, True ])

array([False,  True, False])

In [ ]:
# Not the case that, remainder by 2 is zero
# i.e odd numbers
boolMask = ~ ( arr % 2 == 0 )
arr[ boolMask ]

array([21, 29,  7, 15])

In [ ]:
# elements greater than 10 AND less than 20
boolMask = (arr > 10) & (arr < 20)
arr[ boolMask ]

array([12, 16, 15])

In [ ]:
# elements less than 10 OR greater than 20
boolMask = (arr < 10) | (arr > 20)
arr[ boolMask ]

array([24, 21, 32, 29,  7])

Multiple arrays

In [ ]:
arr

array([12, 24, 16, 21, 32, 29,  7, 15])

In [ ]:
arr2 = np.array([ 7, 12, 20, 25, 30, 30, 5, 2 ])

In [ ]:
boolMask = arr > arr2
boolMask

array([ True,  True, False, False,  True, False,  True,  True])

In [ ]:
# elements in arr greater than arr2, element-wise
arr[ boolMask ]

array([12, 24, 32,  7, 15])

### Recursion

In [ ]:
# see Rosen page 167, Definition 5
# recursive fibonaci
def fib(n):
  if n == 0:
    return 0
  if n == 1:
    return 1

  return fib(n-1) + fib(n-2)

fib(7)

13

Summing elements of a list

In [ ]:
l = [2, 7, 6, 3, 3]

In [ ]:
# sum by looping
mySum = 0
for i in l:
  mySum = mySum + i
mySum

21

$$
listSum(l) = \begin{cases}
    l_1 & \text{if length(l) = 1} \\
    l_1 + listSum(l_{2:n}) & \text{if length(l) > 1}
\end{cases}
$$

In [ ]:
# sum by recursion
def recSum(l):
  # base case. only one element is left
  if len(l) == 1:
    return l[0]

  return l[0] + recSum(l[1:])

In [ ]:
recSum(l)

21

In [3]:
from functools import reduce

In [ ]:
# reduces two numbers to their summation
def foo(x, y):
  return x+y

In [ ]:
# recursively sum the list's elements
reduce( foo, l)

21