# Collaborative Filtering

In [1]:
import numpy as np

In [2]:
# watching record matrix
# user x TV-shows
M = np.array([
    [30, 35, 0, 0],
    [5, 0, 0, 30],
    [0, 0, 32, 20],
    [0, 0, 34, 5]
])

In [3]:
users = np.array([ "Antar", "Tameem", "Logain", "Jumana" ])
tvShows = np.array([ "Game Of Thrones", "Peaky Blenders", "Hannah Montana", "The IT Crowded" ])

Tv-shows seen by Logain `M[2]` but not Tameem `M[1]`.

In [4]:
# tv-shows watched by Logain
M[2] > 0

array([False, False,  True,  True])

In [5]:
# tv-shows not watched by Tameem
M[1] == 0

array([False,  True,  True, False])

In [6]:
# tv-shows watched by Logain but not Tameem
(M[2] > 0) & (M[1] == 0)

array([False, False,  True, False])

In [7]:
# tv-shows names
tvShows[ (M[2] > 0) & (M[1] == 0) ]

array(['Hannah Montana'], dtype='<U15')

Average Episodes Watched

In [8]:
# input. vector u
#        vector v
# output. vector u+v
def addVec(u, v):
  return u + v

In [9]:
from functools import reduce

In [10]:
# add all vectors
reduce( addVec, M )

array([35, 35, 66, 55])

In [11]:
# add vectors and divide by their size
reduce( addVec, M ) / len(M)

array([ 8.75,  8.75, 16.5 , 13.75])

Users who watched episodes more than Jumana

In [12]:
# boolean mask
boolMask = np.array([
  # if episodes sum of user i is greater than Jumana's
  # True is added. Otherwise False is added.
  True if np.sum(i) > np.sum(M[3]) else False
    # loop on each user i (rows of the matrix)
    for i in M
])
boolMask

array([ True, False,  True, False])

In [13]:
users[ boolMask ]

array(['Antar', 'Logain'], dtype='<U6')

## Tasks

- Design an algorithm that takes inputs: user's vector `v` and watching record matrix `M`. Then it fetches top-3 similar users, and computes the weighted average vector of their watching record. Finally it returns tv-shows watched by that neighbourhood not seen by user `v`.
- Design an algorithm that takes inputs: user's vector `v` and watching record matrix `M`. For the tv-show most watched by the user, It fetches similar tv-shows passing some threshold (like 80% cosine similarity or 100 Euclidean Distance), and finally returns them.