**Single-variable function.** Table of values for the difference between two consequent points.

In [ ]:
import numpy as np

In [ ]:
x = np.arange(0.0, 5.0, 1.0)
y = 2 * x

In [ ]:
x

array([0., 1., 2., 3., 4.])

In [ ]:
y

array([0., 2., 4., 6., 8.])

In [ ]:
def rateOfChange( x1, y1, x2, y2 ):
  return (y2 - y1) / (x2 - x1)

def tableOfValues(x, y):
  n = len(x)
  for i in range(n-1):
    print( (y[i+1] - y[i]) / (x[i+1] - x[i]) )

In [ ]:
tableOfValues(x,y)

2.0
2.0
2.0
2.0


**Multi-variable function.** Table of values for the difference between two consequent points, Fixing the other axis.

In [ ]:
# f(a,b) = a^2 + b^2
def f(a,b):
  return a**2 + b**2

# fix f at a = 2
a_0 = 0

# construct sequence x = -5, -4, .., 5
x = np.arange(-5, 6)
# corresponding y, fixing a = 0
y = f(a_0, x)
#y = [ f(a_0, b) for b in x ]

array([25, 16,  9,  4,  1,  0,  1,  4,  9, 16, 25])

In [ ]:
x

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [ ]:
y

[25, 16, 9, 4, 1, 0, 1, 4, 9, 16, 25]

In [ ]:
tableOfValues(x, y)

-9.0
-7.0
-5.0
-3.0
-1.0
1.0
3.0
5.0
7.0
9.0


## Scratch

In [ ]:
l = [0, 2, 4]

In [ ]:
l[1]

2

In [ ]:
def f(x):
  return (2*x) + 7

In [ ]:
[ (2*i) + 7 for i in range(3) ]

[7, 9, 11]

In [ ]:
l = [ f(i) for i in range(3) ]

In [ ]:
import numpy as np

In [ ]:
arr = np.array(l)

In [ ]:
arr

array([ 7,  9, 11])

In [ ]:
arr.sum()

27