## Python & Programming

**List Comprehension**

In [ ]:
l = [2, 4, 6, 8]
l[2]

6

In [ ]:
l = [1, 3, 5, 7]
l

[1, 3, 5, 7]

In [ ]:
for i in range(4):
  print(i)

0
1
2
3


In [ ]:
for i in range(4):
  print(l[i])

1
3
5
7


In [ ]:
l = [ i for i in range(5) ]

In [ ]:
l

[0, 1, 2, 3, 4]

In [ ]:
l = [ 2*i for i in range(5) ]
l

[0, 2, 4, 6, 8]

In [ ]:
ev = [ i for i in range(10) if (i%2 == 0) ]

In [ ]:
ev

[0, 2, 4, 6, 8]

In [ ]:
od = [ i for i in range(10) if not (i%2 == 0) ]

In [ ]:
od

[1, 3, 5, 7, 9]

In [ ]:
[ (2*i) + 1 for i in range(5) ]

[1, 3, 5, 7, 9]

In [ ]:
[ od[i]+ev[i] for i in range(5) ]

[1, 5, 9, 13, 17]

**2d List & Matrix Addition**

In [ ]:
A = [
    [1, 3],
    [2, 4]
  ]

In [ ]:
B = [
    [2, 6],
    [10, 8]
  ]

In [ ]:
B[1][0]

10

In [ ]:
[ A[0][j] + B[0][j] for j in range(2) ]

[3, 9]

In [ ]:
[ A[1][j]+B[1][j] for j in range(2) ]

[12, 12]

In [ ]:
[
    [ A[i][j]+B[i][j] for j in range(2) ]
      for i in range(2)
]

[[3, 9], [12, 12]]

In [ ]:
A

[[1, 3], [2, 4]]

---
## Scratch

construct a 2d list

In [ ]:
l = [ [1, 2, 3], [4, 5, 6] ]

In [ ]:
l[0]

[1, 2, 3]

In [ ]:
l[1]

[4, 5, 6]

In [ ]:
m = []
for i in range(3):
  m.append(l[0][i] + l[1][i])

In [ ]:
m

[5, 7, 9]

In [ ]:
for i in range(2):
  for j in range(2):
    print("(" + str(i) +"," + str(j) + ")")

(0,0)
(0,1)
(1,0)
(1,1)


In [ ]:
"Hello " + str(7)

'Hello 7'

A list of two lists

In [ ]:
M = [
    [1, 2, 3],
    [3, 4, 5]
]

N = [
    [7, 8, 3],
    [3, 9, 5]
]


In [ ]:
M[1][0]

3

In [ ]:
M

[[1, 2, 3], [3, 4, 5]]

In [ ]:
M[1][0] = M[1][0] * 10

In [ ]:
M

[[1, 2, 3], [30, 4, 5]]

In [ ]:
[ i for i in range(5) ]

[0, 1, 2, 3, 4]

In [ ]:
l = [ 2*i for i in range(5) ]

In [ ]:
l

[0, 2, 4, 6, 8]

In [ ]:
l[3]

6

In [ ]:
l[3] = l[3] + 10

In [ ]:
l

[0, 2, 4, 16, 8]

## Scratch

In [ ]:
l = [2, 4, 6, 8]
l[2]

6

In [ ]:
l = [1, 3, 5, 7]
l

[1, 3, 5, 7]

In [ ]:
for i in range(4):
  print(i)

0
1
2
3


In [ ]:
for i in range(4):
  print(l[i])

1
3
5
7


In [ ]:
l = [ i for i in range(5) ]

In [ ]:
l

[0, 1, 2, 3, 4]

In [ ]:
l = [ 2*i for i in range(5) ]
l

[0, 2, 4, 6, 8]

In [ ]:
ev = [ i for i in range(10) if (i%2 == 0) ]

In [ ]:
ev

[0, 2, 4, 6, 8]

In [ ]:
od = [ i for i in range(10) if not (i%2 == 0) ]

In [ ]:
od

[1, 3, 5, 7, 9]

In [ ]:
[ (2*i) + 1 for i in range(5) ]

[1, 3, 5, 7, 9]

In [ ]:
[ od[i]+ev[i] for i in range(5) ]

[1, 5, 9, 13, 17]

In [ ]:
A = [
    [1, 3],
    [2, 4]
  ]

In [ ]:
B = [
    [2, 6],
    [10, 8]
  ]

In [ ]:
B[1][0]

10

In [ ]:
[ A[0][j] + B[0][j] for j in range(2) ]

[3, 9]

In [ ]:
[ A[1][j]+B[1][j] for j in range(2) ]

[12, 12]

In [ ]:
[
    [ A[i][j]+B[i][j] for j in range(2) ]
      for i in range(2)
]

[[3, 9], [12, 12]]

In [ ]:
A

[[1, 3], [2, 4]]

In [ ]:
import numpy as np

In [ ]:
np.array([
    [1, 2],
    [3, 4]
    ])

array([[1, 2],
       [3, 4]])

In [ ]:
A_n = np.array(A)

In [ ]:
A_n

array([[1, 3],
       [2, 4]])

In [ ]:
B_n = np.array( [
    [2,6],
    [10,8]
  ]
)

In [ ]:
B_n

array([[ 2,  6],
       [10,  8]])

In [ ]:
A_n + B_n

array([[ 3,  9],
       [12, 12]])

In [ ]:
np.dot(A_n, B_n)

array([[32, 30],
       [44, 44]])